---
- name: Ensure all directories exits
  when:
    - _home_file.state | default('present') == 'present'
    - _home_file.path | dirname | length > 0
  ansible.builtin.file:
    group: "{{ user.group | default(user.username if users_create_per_user_group else users_group) }}"
    mode: "{{ _home_file.dir_mode | default('0750') }}"
    owner: "{{ user.username }}"
    path: "{{ user.home | default(users_home ~ '/' ~ user.username) }}/{{ _home_file.path | dirname }}"
    state: directory

- name: Create or update file
  when: _home_file.state | default('present') == 'present'
  block:
    - name: Create or update file from template
      when: _home_file.template is defined
      ansible.builtin.template:
        dest: "{{ user.home | default(users_home ~ '/' ~ user.username) }}/{{ _home_file.path }}"
        group: "{{ user.group | default(user.username if users_create_per_user_group else users_group) }}"
        mode: "{{ _home_file.file_mode | default('0640') }}"
        owner: "{{ user.username }}"
        src: "{{ _home_file.template }}"

    - name: Create or update file from content
      when: _home_file.template is not defined
      ansible.builtin.copy:
        content: "{{ _home_file.content }}"
        dest: "{{ user.home | default(users_home ~ '/' ~ user.username) }}/{{ _home_file.path }}"
        group: "{{ user.group | default(user.username if users_create_per_user_group else users_group) }}"
        mode: "{{ _home_file.file_mode | default('0640') }}"
        owner: "{{ user.username }}"

- name: Remove file
  when: _home_file.state | default('present') == 'absent'
  ansible.builtin.file:
    path: "{{ user.home | default(users_home ~ '/' ~ user.username) }}/{{ _home_file.path }}"
    state: absent
