---
- name: Manage groups
  loop: "{{ users_groups }}"
  ansible.builtin.group:
    gid: "{{ item.gid | default(omit) }}"
    local: "{{ item.local | default(omit) }}"
    name: "{{ item.name }}"
    non_unique: "{{ item.non_unique | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    system: "{{ item.system | default(omit) }}"

- name: Manage user
  loop: "{{ users }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"
  ansible.builtin.include_tasks: user.yml
