---
- name: Converge Installation
  hosts: all
  vars:
    users:
      - username: test_delete
        state: absent
        remove: true
        force: true
      - username: test_created
        remove: true
        force: true
        home_files:
          - path: foo/bar
            content: test
  roles:
    - role: finalgene.users
