---
- name: Prepare
  hosts: all
  tasks:
    - name: Create test user exists
      loop:
        test_delete: this user should be deleted
        test_keep: this user should untouched
      ansible.builtin.user:
        name: "{{ item.key }}"
        comment: "{{ item.value }}"
        create_home: true
